name: Pull Request Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: ./gradlew testDebug
