name: Pull Request Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew assembleDebug
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: ./gradlew testDebug
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          path: metador/build/test-results/test/*.xml
  code-analysis:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Android lint
        run: ./gradlew lintDebug
      - name: Spotless
        run: ./gradlew spotlessCheck
