name: Pull Request Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew assembleDebug
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: ./gradlew jvmTest testDebug
      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Kotest Tests
          path: metador/build/test-results/test/*.xml
          reporter: java-junit
  code-analysis:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Android lint
        run: ./gradlew lintDebug
      - name: Spotless
        run: ./gradlew spotlessCheck
